version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: servidor_todo
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: